# Generated by Django 3.1.2 on 2020-12-17 15:22

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201127_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
