# Generated by Django 3.1.2 on 2021-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_offered',
            field=models.TextField(),
        ),
    ]
