# Generated by Django 3.1.2 on 2021-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210106_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_cover_photo_on_view_article',
            field=models.BooleanField(default=True),
        ),
    ]
