# Generated by Django 3.1.2 on 2021-08-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210817_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_image_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
